const express=require("express")
const mongoose=require("mongoose")
const app=express()
const MedecineRoute=require("../backend/router/medecineRouter")
const AdminRoute=require("../backend/router/adminRouter")
const cors=require("cors")
require("dotenv").config()
app.use(express.json())
app.use(cors())
app.use(MedecineRoute)
app.use(AdminRoute)

mongoose.connect(process.env.DB_URL).then(()=> console.log("succes connection.."))
app.listen(5000, ()=>console.log("server is running..."))